### ISSUE TITLE
Plex Error: collection: Trending not found  

### ISSUE THREAD

**Issue by Magikarplvl4** [s0len/meta-manager-config#16]
Hi S0len,

First of all, thank you so much for this configuration. 
I have some small problems running it and i was wondering if you can help me?

Some of the overlays are failing on my side because of a missing plex Trending collection missing.
What is the best way to generate a trending collection? do you have a suggestion?

Issues occurs for movies and tv shows

```shell
[2024-03-10 16:28:25,052] [overlays.py:396]           [INFO]     |=============================== Gathering Items for rt_gold Overlay ================================|
[2024-03-10 16:28:25,052] [overlays.py:404]           [DEBUG]    |                                                                                                    |
[2024-03-10 16:28:25,052] [overlays.py:405]           [DEBUG]    | Builder: plex_search: (1, "Plex Movie Search\nSort By: ['title.asc']\nFilter:\n  Match all of the following:\n    Audience Rating is greater than or equal 9.0\n    Audience Rating is less than or equal 10.0", '?type=1&sort=titleSort&audienceRating%3E=9.0&and=1&audienceRating%3C=10.0') |
[2024-03-10 16:28:25,052] [overlays.py:406]           [INFO]     |                                                                                                    |
[2024-03-10 16:28:25,052] [plex.py:1087]              [INFO]     | Processing Plex Movie Search                                                                       |
                                                                 | Sort By: ['title.asc']                                                                             |
                                                                 | Filter:                                                                                            |
                                                                 |   Match all of the following:                                                                      |
                                                                 |     Audience Rating is greater than or equal 9.0                                                   |
                                                                 |     Audience Rating is less than or equal 10.0                                                     |
[2024-03-10 16:28:26,870] [builder.py:2115]           [DEBUG]    |                                                                                                    |
[2024-03-10 16:28:26,870] [builder.py:2116]           [DEBUG]    | 639 IDs Found                                                                                      |
[2024-03-10 16:28:26,870] [builder.py:2118]           [DEBUG]    |                                                                                                    |
[2024-03-10 16:28:27,361] [overlays.py:426]           [INFO]     | 639 Items found for Overlay File (3) rt_gold                                                       |
[2024-03-10 16:28:27,365] [overlays.py:430]           [INFO]     |                                                                                                    |
[2024-03-10 16:28:27,366] [builder.py:199]            [INFO]     |====================================================================================================|
[2024-03-10 16:28:27,366] [builder.py:199]            [INFO]     |                                rt_bronze_trending Overlay in Movies                                |
[2024-03-10 16:28:27,366] [builder.py:199]            [INFO]     |====================================================================================================|
[2024-03-10 16:28:27,366] [builder.py:200]            [INFO]     |                                                                                                    |
[2024-03-10 16:28:27,366] [builder.py:211]            [INFO]     |================================ Building Definition From Templates ================================|
[2024-03-10 16:28:27,366] [builder.py:212]            [DEBUG]    |                                                                                                    |
[2024-03-10 16:28:27,366] [builder.py:222]            [DEBUG]    | Templates Called: Trending                                                                         |
[2024-03-10 16:28:27,366] [builder.py:223]            [DEBUG]    |                                                                                                    |
[2024-03-10 16:28:27,369] [meta.py:574]               [DEBUG]    |==================================== Final Template Attributes =====================================|
[2024-03-10 16:28:27,369] [meta.py:575]               [DEBUG]    |                                                                                                    |
[2024-03-10 16:28:27,369] [meta.py:576]               [DEBUG]    | {'plex_search': {'all': {'collection': 'Trending', 'audience_rating.gte': 7.0, 'audience_rating.lte': 7.9}}, 'overlay': {'name': 'rt_bronze_trending', 'url': 'https://raw.githubusercontent.com/s0len/meta-manager-config/main/overlays/ribbon-bottom-right/rt_bronze_trending.png', 'group': 'awards', 'weight': 601}, 'tmdb_trending_daily': 100} |
[2024-03-10 16:28:27,369] [meta.py:577]               [DEBUG]    |                                                                                                    |
[2024-03-10 16:28:27,370] [builder.py:239]            [INFO]     |============================= Validating rt_bronze_trending Attributes =============================|
[2024-03-10 16:28:27,374] [plex.py:998]               [DEBUG]    |                                                                                                    |
[2024-03-10 16:28:27,374] [plex.py:1001]              [DEBUG]    | Looking for: rt_bronze_trending                                                                    |
[2024-03-10 16:28:27,374] [overlay.py:96]             [DEBUG]    |                                                                                                    |
[2024-03-10 16:28:27,375] [overlay.py:97]             [DEBUG]    | Validating Method: overlay                                                                         |
[2024-03-10 16:28:27,375] [overlay.py:98]             [DEBUG]    | Value: {'name': 'rt_bronze_trending', 'url': 'https://raw.githubusercontent.com/s0len/meta-manager-config/main/overlays/ribbon-bottom-right/rt_bronze_trending.png', 'group': 'awards', 'weight': 601} |
[2024-03-10 16:28:27,567] [builder.py:959]            [DEBUG]    |                                                                                                    |
[2024-03-10 16:28:27,567] [builder.py:963]            [DEBUG]    | Validating Method: plex_search                                                                     |
[2024-03-10 16:28:27,567] [builder.py:964]            [DEBUG]    | Value: {'all': {'collection': 'Trending', 'audience_rating.gte': 7.0, 'audience_rating.lte': 7.9}} |
[2024-03-10 16:28:27,677] [overlays.py:436]           [DEBUG]    | Traceback (most recent call last):                                                                 |
                                                                 |   File "/modules/builder.py", line 1815, in _plex                                                  |
                                                                 |     self.builders.append((method_name, self.build_filter("plex_search", dict_data)))               |
                                                                 |                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                 |
                                                                 |   File "/modules/builder.py", line 2510, in build_filter                                           |
                                                                 |     built_filter, filter_text = _filter(base_dict, is_all=base_all)                                |
                                                                 |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                |
                                                                 |   File "/modules/builder.py", line 2449, in _filter                                                |
                                                                 |     validation = self.validate_attribute(attr, modifier, final_attr, _data, validate, plex_search=True) |
                                                                 |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ |
                                                                 |   File "/modules/builder.py", line 2634, in validate_attribute                                     |
                                                                 |     raise FilterFailed(error)                                                                      |
                                                                 | modules.util.FilterFailed: Plex Error: collection: Trending not found                              |
                                                                 |                                                                                                    |
                                                                 | During handling of the above exception, another exception occurred:                                |
                                                                 |                                                                                                    |
                                                                 | Traceback (most recent call last):                                                                 |
                                                                 |   File "/modules/overlays.py", line 393, in compile_overlays                                       |
                                                                 |     builder = CollectionBuilder(self.config, overlay_file, k, v, library=self.library, overlay=True) |
                                                                 |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ |
                                                                 |   File "/modules/builder.py", line 1041, in __init__                                               |
                                                                 |     self._plex(method_name, method_data)                                                           |
                                                                 |   File "/modules/builder.py", line 1820, in _plex                                                  |
                                                                 |     raise Failed(str(e))                                                                           |
                                                                 | modules.util.Failed: Plex Error: collection: Trending not found                                    |
                                                                 |                                                                                                    |
[2024-03-10 16:28:27,679] [overlays.py:437]           [ERROR]    | Plex Error: collection: Trending not found                                                         |
[2024-03-10 16:28:27,679] [overlays.py:438]           [INFO]     |                                                                                                    |
[2024-03-10 16:28:27,679] [builder.py:199]            [INFO]     |====================================================================================================|
[2024-03-10 16:28:27,679] [builder.py:199]            [INFO]     |                                rt_silver_trending Overlay in Movies                                |
[2024-03-10 16:28:27,679] [builder.py:199]            [INFO]     |====================================================================================================|
[2024-03-10 16:28:27,680] [builder.py:200]            [INFO]     |                                                                                                    |
[2024-03-10 16:28:27,680] [builder.py:211]            [INFO]     |================================ Building Definition From Templates ================================|
[2024-03-10 16:28:27,680] [builder.py:212]            [DEBUG]    |                                                                                                    |
[2024-03-10 16:28:27,680] [builder.py:222]            [DEBUG]    | Templates Called: Trending                                                                         |
[2024-03-10 16:28:27,680] [builder.py:223]            [DEBUG]    |                                                                                                    |
[2024-03-10 16:28:27,683] [meta.py:574]               [DEBUG]    |==================================== Final Template Attributes =====================================|
[2024-03-10 16:28:27,683] [meta.py:575]               [DEBUG]    |                                                                                                    |
[2024-03-10 16:28:27,683] [meta.py:576]               [DEBUG]    | {'plex_search': {'all': {'collection': 'Trending', 'audience_rating.gte': 8.0, 'audience_rating.lte': 8.9}}, 'overlay': {'name': 'rt_silver_trending', 'url': 'https://raw.githubusercontent.com/s0len/meta-manager-config/main/overlays/ribbon-bottom-right/rt_silver_trending.png', 'group': 'awards', 'weight': 602}, 'tmdb_trending_daily': 100} |
[2024-03-10 16:28:27,683] [meta.py:577]               [DEBUG]    |                                                                                                    |
[2024-03-10 16:28:27,683] [builder.py:239]            [INFO]     |============================= Validating rt_silver_trending Attributes =============================|
[2024-03-10 16:28:27,688] [plex.py:998]               [DEBUG]    |                                                                                                    |
[2024-03-10 16:28:27,688] [plex.py:1001]              [DEBUG]    | Looking for: rt_silver_trending                                                                    |
[2024-03-10 16:28:27,689] [overlay.py:96]             [DEBUG]    |                                                                                                    |
[2024-03-10 16:28:27,689] [overlay.py:97]             [DEBUG]    | Validating Method: overlay                                                                         |
[2024-03-10 16:28:27,689] [overlay.py:98]             [DEBUG]    | Value: {'name': 'rt_silver_trending', 'url': 'https://raw.githubusercontent.com/s0len/meta-manager-config/main/overlays/ribbon-bottom-right/rt_silver_trending.png', 'group': 'awards', 'weight': 602} |
[2024-03-10 16:28:27,859] [builder.py:959]            [DEBUG]    |                                                                                                    |
[2024-03-10 16:28:27,859] [builder.py:963]            [DEBUG]    | Validating Method: plex_search                                                                     |
[2024-03-10 16:28:27,859] [builder.py:964]            [DEBUG]    | Value: {'all': {'collection': 'Trending', 'audience_rating.gte': 8.0, 'audience_rating.lte': 8.9}} |
[2024-03-10 16:28:27,895] [overlays.py:436]           [DEBUG]    | Traceback (most recent call last):                                                                 |
                                                                 |   File "/modules/builder.py", line 1815, in _plex                                                  |
                                                                 |     self.builders.append((method_name, self.build_filter("plex_search", dict_data)))               |
                                                                 |                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                 |
                                                                 |   File "/modules/builder.py", line 2510, in build_filter                                           |
                                                                 |     built_filter, filter_text = _filter(base_dict, is_all=base_all)                                |
                                                                 |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                |
                                                                 |   File "/modules/builder.py", line 2449, in _filter                                                |
                                                                 |     validation = self.validate_attribute(attr, modifier, final_attr, _data, validate, plex_search=True) |
                                                                 |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ |
                                                                 |   File "/modules/builder.py", line 2634, in validate_attribute                                     |
                                                                 |     raise FilterFailed(error)                                                                      |
                                                                 | modules.util.FilterFailed: Plex Error: collection: Trending not found                              |
                                                                 |                                                                                                    |
                                                                 | During handling of the above exception, another exception occurred:                                |
                                                                 |                                                                                                    |
                                                                 | Traceback (most recent call last):                                                                 |
                                                                 |   File "/modules/overlays.py", line 393, in compile_overlays                                       |
                                                                 |     builder = CollectionBuilder(self.config, overlay_file, k, v, library=self.library, overlay=True) |
                                                                 |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ |
                                                                 |   File "/modules/builder.py", line 1041, in __init__                                               |
                                                                 |     self._plex(method_name, method_data)                                                           |
                                                                 |   File "/modules/builder.py", line 1820, in _plex                                                  |
                                                                 |     raise Failed(str(e))                                                                           |
                                                                 | modules.util.Failed: Plex Error: collection: Trending not found                                    |
                                                                 |                                                                                                    |
[2024-03-10 16:28:27,897] [overlays.py:437]           [ERROR]    | Plex Error: collection: Trending not found                                                         |
[2024-03-10 16:28:27,897] [overlays.py:438]           [INFO]     |                                                                                                    |
[2024-03-10 16:28:27,897] [builder.py:199]            [INFO]     |====================================================================================================|
[2024-03-10 16:28:27,897] [builder.py:199]            [INFO]     |                                 rt_gold_trending Overlay in Movies                                 |
[2024-03-10 16:28:27,897] [builder.py:199]            [INFO]     |====================================================================================================|
[2024-03-10 16:28:27,897] [builder.py:200]            [INFO]     |                                                                                                    |
[2024-03-10 16:28:27,897] [builder.py:211]            [INFO]     |================================ Building Definition From Templates ================================|
[2024-03-10 16:28:27,898] [builder.py:212]            [DEBUG]    |                                                                                                    |
[2024-03-10 16:28:27,898] [builder.py:222]            [DEBUG]    | Templates Called: Trending                                                                         |
[2024-03-10 16:28:27,898] [builder.py:223]            [DEBUG]    |                                                                                                    |
[2024-03-10 16:28:27,900] [meta.py:574]               [DEBUG]    |==================================== Final Template Attributes =====================================|
[2024-03-10 16:28:27,901] [meta.py:575]               [DEBUG]    |                                                                                                    |
[2024-03-10 16:28:27,901] [meta.py:576]               [DEBUG]    | {'plex_search': {'all': {'collection': 'Trending', 'audience_rating.gte': 9.0, 'audience_rating.lte': 10}}, 'overlay': {'name': 'rt_gold_trending', 'url': 'https://raw.githubusercontent.com/s0len/meta-manager-config/main/overlays/ribbon-bottom-right/rt_gold_trending.png', 'group': 'awards', 'weight': 603}, 'tmdb_trending_daily': 100} |
[2024-03-10 16:28:27,901] [meta.py:577]               [DEBUG]    |                                                                                                    |
[2024-03-10 16:28:27,901] [builder.py:239]            [INFO]     |============================== Validating rt_gold_trending Attributes ==============================|
[2024-03-10 16:28:27,905] [plex.py:998]               [DEBUG]    |                                                                                                    |
[2024-03-10 16:28:27,905] [plex.py:1001]              [DEBUG]    | Looking for: rt_gold_trending                                                                      |
[2024-03-10 16:28:27,905] [overlay.py:96]             [DEBUG]    |                                                                                                    |
[2024-03-10 16:28:27,905] [overlay.py:97]             [DEBUG]    | Validating Method: overlay                                                                         |
[2024-03-10 16:28:27,905] [overlay.py:98]             [DEBUG]    | Value: {'name': 'rt_gold_trending', 'url': 'https://raw.githubusercontent.com/s0len/meta-manager-config/main/overlays/ribbon-bottom-right/rt_gold_trending.png', 'group': 'awards', 'weight': 603} |
[2024-03-10 16:28:28,083] [builder.py:959]            [DEBUG]    |                                                                                                    |
[2024-03-10 16:28:28,083] [builder.py:963]            [DEBUG]    | Validating Method: plex_search                                                                     |
[2024-03-10 16:28:28,083] [builder.py:964]            [DEBUG]    | Value: {'all': {'collection': 'Trending', 'audience_rating.gte': 9.0, 'audience_rating.lte': 10}}  |
[2024-03-10 16:28:28,118] [overlays.py:436]           [DEBUG]    | Traceback (most recent call last):                                                                 |
                                                                 |   File "/modules/builder.py", line 1815, in _plex                                                  |
                                                                 |     self.builders.append((method_name, self.build_filter("plex_search", dict_data)))               |
                                                                 |                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                 |
                                                                 |   File "/modules/builder.py", line 2510, in build_filter                                           |
                                                                 |     built_filter, filter_text = _filter(base_dict, is_all=base_all)                                |
                                                                 |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                |
                                                                 |   File "/modules/builder.py", line 2449, in _filter                                                |
                                                                 |     validation = self.validate_attribute(attr, modifier, final_attr, _data, validate, plex_search=True) |
                                                                 |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ |
                                                                 |   File "/modules/builder.py", line 2634, in validate_attribute                                     |
                                                                 |     raise FilterFailed(error)                                                                      |
                                                                 | modules.util.FilterFailed: Plex Error: collection: Trending not found                              |
                                                                 |                                                                                                    |
                                                                 | During handling of the above exception, another exception occurred:                                |
                                                                 |                                                                                                    |
                                                                 | Traceback (most recent call last):                                                                 |
                                                                 |   File "/modules/overlays.py", line 393, in compile_overlays                                       |
                                                                 |     builder = CollectionBuilder(self.config, overlay_file, k, v, library=self.library, overlay=True) |
                                                                 |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ |
                                                                 |   File "/modules/builder.py", line 1041, in __init__                                               |
                                                                 |     self._plex(method_name, method_data)                                                           |
                                                                 |   File "/modules/builder.py", line 1820, in _plex                                                  |
                                                                 |     raise Failed(str(e))                                                                           |
                                                                 | modules.util.Failed: Plex Error: collection: Trending not found                                    |
                                                                 |                                                                                                    |
[2024-03-10 16:28:28,120] [overlays.py:437]           [ERROR]    | Plex Error: collection: Trending not found                                                         |
[2024-03-10 16:28:28,121] [overlays.py:438]           [INFO]     |                                                                                                    |
[2024-03-10 16:28:28,121] [builder.py:199]            [INFO]     |====================================================================================================|
[2024-03-10 16:28:28,121] [builder.py:199]            [INFO]     |                                  trendingMovies Overlay in Movies                                  |
[2024-03-10 16:28:28,121] [builder.py:199]            [INFO]     |====================================================================================================|
[2024-03-10 16:28:28,121] [builder.py:200]            [INFO]     |                                                                                                    |
[2024-03-10 16:28:28,121] [builder.py:211]            [INFO]     |================================ Building Definition From Templates ================================|
[2024-03-10 16:28:28,121] [builder.py:212]            [DEBUG]    |                                                                                                    |
[2024-03-10 16:28:28,121] [builder.py:222]            [DEBUG]    | Templates Called: Trending                                                                         |
[2024-03-10 16:28:28,121] [builder.py:223]            [DEBUG]    |                                                                                                    |
[2024-03-10 16:28:28,124] [meta.py:574]               [DEBUG]    |==================================== Final Template Attributes =====================================|
[2024-03-10 16:28:28,124] [meta.py:575]               [DEBUG]    |                                                                                                    |
[2024-03-10 16:28:28,124] [meta.py:576]               [DEBUG]    | {'plex_search': {'all': {'collection': 'Trending', 'audience_rating.gte': '', 'audience_rating.lte': ''}}, 'overlay': {'name': 'trendingMovies', 'url': 'https://raw.githubusercontent.com/s0len/meta-manager-config/main/overlays/ribbon-bottom-right/trendingMovies.png', 'group': 'awards', 'weight': 400}, 'tmdb_trending_daily': '<<tmdbTrendDaily>>'} |
[2024-03-10 16:28:28,124] [meta.py:577]               [DEBUG]    |                                                                                                    |
[2024-03-10 16:28:28,125] [builder.py:239]            [INFO]     |=============================== Validating trendingMovies Attributes ===============================|
[2024-03-10 16:28:28,129] [plex.py:998]               [DEBUG]    |                                                                                                    |
[2024-03-10 16:28:28,130] [plex.py:1001]              [DEBUG]    | Looking for: trendingMovies                                                                        |
[2024-03-10 16:28:28,130] [overlay.py:96]             [DEBUG]    |                                                                                                    |
[2024-03-10 16:28:28,130] [overlay.py:97]             [DEBUG]    | Validating Method: overlay                                                                         |
[2024-03-10 16:28:28,130] [overlay.py:98]             [DEBUG]    | Value: {'name': 'trendingMovies', 'url': 'https://raw.githubusercontent.com/s0len/meta-manager-config/main/overlays/ribbon-bottom-right/trendingMovies.png', 'group': 'awards', 'weight': 400} |
[2024-03-10 16:28:28,305] [builder.py:959]            [DEBUG]    |                                                                                                    |
[2024-03-10 16:28:28,305] [builder.py:963]            [DEBUG]    | Validating Method: plex_search                                                                     |
[2024-03-10 16:28:28,305] [builder.py:964]            [DEBUG]    | Value: {'all': {'collection': 'Trending', 'audience_rating.gte': '', 'audience_rating.lte': ''}}   |
[2024-03-10 16:28:28,345] [overlays.py:436]           [DEBUG]    | Traceback (most recent call last):                                                                 |
                                                                 |   File "/modules/builder.py", line 1815, in _plex                                                  |
                                                                 |     self.builders.append((method_name, self.build_filter("plex_search", dict_data)))               |
                                                                 |                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                 |
                                                                 |   File "/modules/builder.py", line 2510, in build_filter                                           |
                                                                 |     built_filter, filter_text = _filter(base_dict, is_all=base_all)                                |
                                                                 |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                |
                                                                 |   File "/modules/builder.py", line 2449, in _filter                                                |
                                                                 |     validation = self.validate_attribute(attr, modifier, final_attr, _data, validate, plex_search=True) |
                                                                 |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ |
                                                                 |   File "/modules/builder.py", line 2634, in validate_attribute                                     |
                                                                 |     raise FilterFailed(error)                                                                      |
                                                                 | modules.util.FilterFailed: Plex Error: collection: Trending not found                              |
                                                                 |                                                                                                    |
                                                                 | During handling of the above exception, another exception occurred:                                |
                                                                 |                                                                                                    |
                                                                 | Traceback (most recent call last):                                                                 |
                                                                 |   File "/modules/overlays.py", line 393, in compile_overlays                                       |
                                                                 |     builder = CollectionBuilder(self.config, overlay_file, k, v, library=self.library, overlay=True) |
                                                                 |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ |
                                                                 |   File "/modules/builder.py", line 1041, in __init__                                               |
                                                                 |     self._plex(method_name, method_data)                                                           |
                                                                 |   File "/modules/builder.py", line 1820, in _plex                                                  |
                                                                 |     raise Failed(str(e))                                                                           |
                                                                 | modules.util.Failed: Plex Error: collection: Trending not found                                    |
                                                                 |                                                                                                    |
[2024-03-10 16:28:28,347] [overlays.py:437]           [ERROR]    | Plex Error: collection: Trending not found                                                         |
[2024-03-10 16:28:28,347] [overlays.py:438]           [INFO]     |                                                                                                    |"

```

I am using the
url: https://raw.githubusercontent.com/s0len/meta-manager-config/main/overlays/status.yml
url: https://raw.githubusercontent.com/s0len/meta-manager-config/main/overlays/ribbon_trending.yml
url: https://raw.githubusercontent.com/s0len/meta-manager-config/main/overlays/ribbon_rotten.yml

**Comment by s0len** [comment]
This has finally been fixed, sorry for the delay @Magikarplvl4
